// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kepvtlgmtwhjsryfqexg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlcHZ0bGdtdHdoanNyeWZxZXhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzMxNjIsImV4cCI6MjA2NTUwOTE2Mn0.ET4r3HCZOP-9uddMergtO1n6baHqxd3r2Fq6F5wQF7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);